name: Deploy

on: workflow_dispatch

env:
  GC_REGION: us-central1
  AR_LOCATION: ${{ secrets.SCA_APP_AR_LOCATION }}
  GC_SERVICE: ${{ secrets.SCA_APP_GC_SERVICE }}

permissions:
  contents: read
  id-token: write

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - name: Authenticate with Workload Identity Federation
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/535434239234/locations/global/workloadIdentityPools/wip-github-actions-sandbox/providers/sca-github-oidc-sandbox"
          service_account: "wip-sca-github-action-sandbox@sca-sandbox.iam.gserviceaccount.com"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: "Use gcloud CLI"
        run: "gcloud info"

      - name: "Docker auth"
        run: |-
          gcloud auth configure-docker ${{ secrets.SCA_APP_AR_REGION }}-docker.pkg.dev --quiet

      # - name: Make envfile
      #   run: |
      #     touch .env
      #     echo "${{ secrets.SCA_APP_ENV }}" > .env
      #     cat .env
        
      - name: "Build image"
        run: docker build -t ${{ secrets.SCA_APP_AR_LOCATION }}:$GITHUB_SHA .

      - name: "Push image"
        run: docker push ${{ secrets.SCA_APP_AR_LOCATION }}:$GITHUB_SHA
        
      - name: "Deploy"
        run: |-
          gcloud run deploy ${{ secrets.SCA_APP_GC_SERVICE }} \
          --image ${{ secrets.SCA_APP_AR_LOCATION }}:$GITHUB_SHA \
          --region $GC_REGION \
          --quiet